# -*- coding: utf-8 -*-
"""Aula 02/03/2022n (SQL).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4AzzQ84qkY27m1-Zf0O5qOmCfk-aM3K
"""

import sqlite3

conn = sqlite3.connect('euBanco.db')
print("Conexão aberta!")

conn.execute ('''
  CREATE TABLE IF NOT EXISTS alunos (
    matricula integer,
    nome string,
    nota integer
  );
''') 
conn.commit() 
print("Tabela criada com sucesso!")

conn.execute("INSERT INTO alunos VALUES(1, 'Angelica' ,10);")
conn.execute("INSERT INTO alunos VALUES(2, 'Jefferson' ,8);")
conn.execute("INSERT INTO alunos VALUES(3, 'Hildegard' ,9);")
conn.execute("INSERT INTO alunos VALUES(4, 'Renan' ,7);")
conn.execute("INSERT INTO alunos VALUES(5, 'Vantuil' ,7);")
conn.execute("INSERT INTO alunos VALUES(6, 'Rafael' ,8);")
conn.execute("INSERT INTO alunos VALUES(7, 'Janaina' ,10);")

conn.commit()
print("Dados incluidos com sucesso!")

import pandas as pd

dadosAlunos = conn.execute('''
  SELECT matricula , nome , nota 
  FROM alunos;
''')

for aluno in dadosAlunos:
  print("Matricula:",aluno[0])
  print("Nome:",aluno[1])
  print("Nota:",aluno[2], "\n")

conn.close()