# -*- coding: utf-8 -*-
"""CePython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1elUGYMxNZ4D9kXdfxznw-mTdMiSeYPHw
"""

import requests

def buscaCep():
  print("---------------CEPYTHON 0.0.1-------------")
  cep = input('Digite o cep desejado: ')
  resultado = requests.get('https://viacep.com.br/ws/{}/json/'.format(cep))
  endereco = resultado.json()

  print("======> CEP Encontrado! <======")
  print('CEP: {}'.format(endereco['cep']))
  print(f"Cidade:{endereco['localidade']}")
  print('Estado:',endereco['uf'])

buscaCep()  
rodar = True
while rodar:
  print("Você deseja consultar outro CEP?")
  resposta = input("1 -sim \n 2 - não")
  if resposta == "1" :
    buscaCep()  
  else:
      rodar = False
      print("Obrigado por usar minha aplicação! Até mais!")