# -*- coding: utf-8 -*-
"""Stock_Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/168q7kFrDizmm2LEwO31sZ8hntT7dU7Z5
"""

import requests
import pandas as pd
import matplotlib.pyplot as plt

#minha api_Key para a alfa vantage , mas por enquanto funciona sem..
api_Key = "AQE9FYOD4HR674NF"

#buscar os dados da ação
url = "https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=GOOGL&apikey={api_key}"
dados = requests.get(url)
resultado = dados.json()

#converter os dados para a estrutura de um dataframe
df = pd.DataFrame (resultado["Time Series (Daily)"]).T
df.index = pd.to_datetime(df.index)

#selecionar os dados dos últimos 30 dias
df = df.loc[df.index > (df.index[0] - pd.Timedelta(days=30))]

#calcular a variação da cotação
df["variacao"] = (df["4. close"].astype(float) - df["1. open"].astype(float)) / df["1. open"].astype(float)

#ordenar pelo maior lucro
df = df.sort_values('variacao', ascending=False)

#selecionar  as 10 melhores ações
top_10 = df.head(10)

#mostrar o top 10
print(top_10[['variacao']]) 

#mostrar o grafico
top_10["4. close"].astype(float).plot()